version: '2'
volumes:
  db:
  solr:
services:
  base:
    image: node:12
    volumes:
      - .:/home/app
    working_dir: /home/app
  install:
    extends:
      service: base
    command: npm install --unsafe-perm
  build:
    extends:
      service: base
    command: npm run build
  bash:
    extends:
      service: base
    stdin_open: true
    tty: true
    command: /bin/bash