version: '3'
volumes:
  db:
  solr:
  solr_config:
  data:
services:
  web:
    image: derhenning/mopsy:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - /volume1/media/books:/mnt/books:ro
      - data:/mnt/data:ro
    environment:
      MOPSY_APP_NAME: MOPSY Search
      MOPSY_PORT: 80
      MOPSY_JSON_IDENTATION: 4
      MOPSY_MYSQL_DATABASE: mopsy
      MOPSY_MYSQL_HOST: db
      MOPSY_MYSQL_PORT: 3306
      MOPSY_MYSQL_USERNAME: mopsy
      MOPSY_MYSQL_PASSWORD: mopsy
      MOPSY_SOLR_HOST: solr
      MOPSY_SOLR_PORT: 8983
      MOPSY_SOLR_CORE: mopsy
      MOPSY_MYPRIVATEKEY: myprivatekey
      MOPSY_SESSIONKEY: myprivatekey
      MOPSY_SALT_ROUNDS: 10
      MOPSY_HITS_PER_PAGE: 10
      MOPSY_CRAWLERS: calibre,filesystem
      REDIS_HOST: redis
      REDIS_PORT: 6379
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: mopsy
      MYSQL_PASSWORD: mopsy
      MYSQL_DATABASE: mopsy
      MYSQL_USER: mopsy
  redis:
    image: redis
  solr:
    image: solr:8.6
    restart: always
    environment:
      - SOLR_HEAP=2g
    volumes:
      - solr:/var/solr:rw
      - solr_config:/opt/solr/server/solr/configsets/myconfig:ro
    command:
      solr-precreate mopsy /opt/solr/server/solr/configsets/myconfig
  calibre:
    image: derhenning/mopsy-crawler:latest
    volumes:
      - /volume1/media/books:/mnt/books:ro
      - data:/mnt/data:rw
    environment:
      CRAWLER_TYPE: calibre
      CRAWLER_NAME: Calibre V1.0
      CALIBRE_PATH: /mnt/books
      MOPSY_SOLR_HOST: solr
      MOPSY_SOLR_PORT: 8983
      MOPSY_SOLR_CORE: mopsy
      MOPSY_SOLR_PREFIX: calibre
  filesystem:
    image: derhenning/mopsy-crawler:latest
    networks:
      dev:
    volumes:
      - /volume1/media/bib:/mnt/books:ro
      - data-dev:/mnt/data:rw
    environment:
      DEBUG: 'true'
      CRAWLER_TYPE: filesystem
      CRAWLER_NAME: Filesystem V1.0
      ROOT_FOLDER: /mnt/books/
      CRAWLER_SLEEP_TIME: 1
      MOPSY_SOLR_HOST: solr
      MOPSY_SOLR_PORT: 8983
      MOPSY_SOLR_CORE: mopsy
      MOPSY_SOLR_PREFIX: files