version: '2'
networks:
  dev:
services:
  base:
    image: node:14
    volumes:
      - .:/home/app
    working_dir: /home/app
    networks:
      dev:
  install:
    extends:
      service: base
    command: npm install --unsafe-perm
  build:
    extends:
      service: base
    command: npm run build
  bash:
    extends:
      service: base
    stdin_open: true
    tty: true
    command: /bin/bash
  schema:
    image: crawler:dev
    command: python buildSchema.py