version: "3"
volumes:
  db-dev:
  solr-dev:
  data-dev:
  calibre:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '~/Calibre-Bibliothek'
  files:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '~/Calibre-Bibliothek'
services:
  mopsy:
    image: node:14
    ports:
      - 1234:3000
      - 1236:4000
    command: npm run dev
    volumes:
      - ./:/home/app
      - calibre:/mnt/calibre:ro
      - files:/mnt/files:ro
      - data-dev:/mnt/data
    working_dir: /home/app
    environment:
      DANGEROUSLY_DISABLE_HOST_CHECK: "true"
      MOPSY_APP_NAME: MOPSY Search
      MOPSY_JSON_IDENTATION: 4
      MOPSY_MYSQL_DATABASE: mopsy
      MOPSY_MYSQL_HOST: db
      MOPSY_MYSQL_PORT: 3306
      MOPSY_MYSQL_USERNAME: mopsy
      MOPSY_MYSQL_PASSWORD: mopsy
      MOPSY_SOLR_HOST: solr
      MOPSY_SOLR_PORT: 8983
      MOPSY_SOLR_CORE: mopsy
      MOPSY_SESSIONKEY: myprivatekey
      MOPSY_SALT_ROUNDS: 10
      MOPSY_HITS_PER_PAGE: 10
      MOPSY_CRAWLERS: calibre,filesystem
      REDIS_HOST: redis
      REDIS_PORT: 6379
  db:
    image: mariadb:10.6
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db-dev:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mopsy
      - MYSQL_PASSWORD=mopsy
      - MYSQL_DATABASE=mopsy
      - MYSQL_USER=mopsy
  redis:
    image: redis:6
  adminer:
    image: adminer
    ports:
      - 1237:8080
  solr:
    image: solr:8.6
    ports:
      - 1235:8983
    volumes:
      - solr-dev:/var/solr
      - ./solr_configset:/opt/solr/server/solr/configsets/myconfig:ro
    environment:
      - SOLR_HEAP=1g
    command:
      solr-precreate mopsy /opt/solr/server/solr/configsets/myconfig
  calibre:
    #image: derhenning/mopsy-crawler:latest
    image: crawler:dev
    ports:
      - 1238:80
    volumes:
      - calibre:/mnt/calibre:ro
      - data-dev:/mnt/data
    environment:
      DEBUG: 'true'
      CRAWLER_TYPE: calibre
      CRAWLER_NAME: Calibre V1.0
      CALIBRE_PATH: /mnt/calibre
      CRAWLER_SLEEP_TIME: 1
      MOPSY_SOLR_HOST: solr
      MOPSY_SOLR_PORT: 8983
      MOPSY_SOLR_CORE: mopsy
      MOPSY_SOLR_PREFIX: calibre
  filesystem:
    #image: derhenning/mopsy-crawler:latest
    image: crawler:dev
    volumes:
      - files:/mnt/files:ro
      - data-dev:/mnt/data
    environment:
      DEBUG: 'true'
      CRAWLER_TYPE: filesystem
      CRAWLER_NAME: Filesystem V1.0
      ROOT_FOLDER: /mnt/files
      CRAWLER_SLEEP_TIME: 1
      MOPSY_SOLR_HOST: solr
      MOPSY_SOLR_PORT: 8983
      MOPSY_SOLR_CORE: mopsy
      MOPSY_SOLR_PREFIX: files