version: '3'
volumes:
  db:     # volume for database - it is recomended to mount an external folder
  solr:   # volume for solr index - it is recommendet to mount an external folder
  cache:  # volume for cached pdf files. only applies for web scraping crawlers
services:
  api:
    image: derhenning/mopsy:latest
    restart: unless-stopped
    ports:
      - 80:80     ## it is recomended to use a reverse proxy with ssl encryption
    volumes:
      - ./books:/mnt/calibre:ro    ## change ./books to path to your calibre db folder
      - cache:/cache:ro
    environment:
      MOPSY_APP_NAME: MOPSY Search
      MOPSY_DB_PASSWORD: myverygoodpassword
      MOPSY_SESSIONKEY: myprivatekey
      MOPSY_CRAWLERS: calibre    ## hostnames of used crawlers
  db:
    image: postgres:9.6
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: myverygoodpassword
      POSTGRES_USER: mopsy
      POSTGRES_DB: mopsy
  redis:
    image: redis:6.2
    restart: unless-stopped
  solr:
    image: solr:8.11
    restart: unless-stopped
    environment:
      - SOLR_HEAP=2g
    volumes:
      - solr:/var/solr:rw
      - ./solr_configset:/opt/solr/server/solr/configsets/myconfig:ro
    command:
      solr-precreate mopsy /opt/solr/server/solr/configsets/myconfig

###       Crawler for Calibre DB   --   delete if not needed
  calibre:
    image: derhenning/mopsy-crawler:latest
    restart: unless-stopped
    volumes:
      - ./books:/mnt/calibre:ro    ### change ./books to path to your calibre db folder
      - cache:/cache:rw
    environment:
      CRAWLER_TYPE: calibre
      CRAWLER_NAME: Calibre V1.0
      CALIBRE_PATH: /mnt/calibre
      CRAWLER_SLEEP_TIME: 1
      MOPSY_SOLR_PREFIX: calibre