ARG PYTHON_VERSION="3.10-slim"

FROM python:${PYTHON_VERSION}

COPY ./crawler/requirements.txt /tmp/pip-tmp/

RUN pip3 --disable-pip-version-check --no-cache-dir install -r /tmp/pip-tmp/requirements.txt \
    && rm -rf /tmp/pip-tmp

RUN mkdir /cache
VOLUME /cache

WORKDIR /app
