name: Publish Docker dev Image

on:
    push:
        branches:
            - dev

jobs:
    release:
        name: Release Image
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                image: [ 'mopsy', 'mopsy-crawler' ]
        steps:
        -
            name: Checkout
            uses: actions/checkout@v1
        -
            name: Set Release Tag
            run: |
                echo "RELEASE_TAG=dev" >> $GITHUB_ENV
        -
            name: Set up QEMU
            uses: docker/setup-qemu-action@v1
            with:
                platforms: all
        -
            name: Set up Docker Buildx
            id: buildx
            uses: docker/setup-buildx-action@v1
        -
            name: Login to DockerHub
            uses: docker/login-action@v1
            with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
        -
            name: Build and push image
            uses: docker/build-push-action@v2
            with:
                context: .
                file: ./docker/Dockerfile.${{ matrix.image }}
                platforms: linux/amd64
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.image }}:${{ env.RELEASE_TAG }}
