name: Publish multi-arch Docker images

on:
    push:
        branches:
            - master
        tags:
            - '*'

jobs:
    release:
        name: Release Image
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                image: [ 'mopsy', 'mopsy-crawler' ]
        steps:
        -
            name: Checkout
            uses: actions/checkout@v1
        -
            name: Set Release Tag
            run: |
                if [ "${GITHUB_REF#refs/*/}" = "master" ]; \
                then echo "RELEASE_TAG=latest"; \
                else echo "RELEASE_TAG=${GITHUB_REF#refs/*/}"; fi \
                >> $GITHUB_ENV
        -
            name: Set up QEMU
            uses: docker/setup-qemu-action@v1
            with:
                platforms: all
        -
            name: Set up Docker Buildx
            id: buildx
            uses: docker/setup-buildx-action@v1
        -
            name: Login to DockerHub
            uses: docker/login-action@v1
            with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
        -
            name: Build and push image
            uses: docker/build-push-action@v2
            with:
                context: .
                file: ./docker/Dockerfile.${{ matrix.image }}
                platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.image }}:${{ env.RELEASE_TAG }}
